name: check for updated base image

on:
  schedule:
    - cron:  '0 0 * * 4'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: codercom/code-server:latest
          image: devusb/code-server-plus:latest
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.check.outputs.needs-updating == 'true'
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: devusb/code-server-plus:latest
        if: steps.check.outputs.needs-updating == 'true'