name: check docker images

on:
  schedule:
    - cron:  '0 0 * * 4'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: codercom/code-server:latest
          image: devusb/code-server-plus:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: devusb/code-server-plus:latest
        if: steps.check.outputs.needs-updating == 'true'